/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/**
 *
 * @author ASUS
 */
public class DataPasien extends javax.swing.JFrame {

    /**
     * Creates new form EditDataPasien
     */
    public DataPasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JBMenuUtama3 = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jLdaftarPasien6 = new javax.swing.JLabel();
        jLdftrIDPasien4 = new javax.swing.JLabel();
        jLdftrNama4 = new javax.swing.JLabel();
        jLdftrtglLhr4 = new javax.swing.JLabel();
        jLdftrUmur4 = new javax.swing.JLabel();
        jTFidPasien7 = new javax.swing.JTextField();
        jTFNamaPasien7 = new javax.swing.JTextField();
        jTFtglLahirPasien7 = new javax.swing.JTextField();
        jTFUmur7 = new javax.swing.JTextField();
        jLdftrIDPasien9 = new javax.swing.JLabel();
        jTFidPasien12 = new javax.swing.JTextField();
        JBSearchPasienID = new javax.swing.JButton();
        JBMenuUtama1 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLdaftarPasien11 = new javax.swing.JLabel();
        jLdftrIDPasien10 = new javax.swing.JLabel();
        jLdftrNama9 = new javax.swing.JLabel();
        jLdftrtglLhr9 = new javax.swing.JLabel();
        jLdftrUmur9 = new javax.swing.JLabel();
        jTFidPasien13 = new javax.swing.JTextField();
        jTFNamaPasien12 = new javax.swing.JTextField();
        jTFtglLahirPasien12 = new javax.swing.JTextField();
        jTFUmur12 = new javax.swing.JTextField();
        jLdftrIDPasien11 = new javax.swing.JLabel();
        jTFidPasien14 = new javax.swing.JTextField();
        JBAddPasien8 = new javax.swing.JButton();
        JBMenuUtama2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLdaftarPasien9 = new javax.swing.JLabel();
        jLdftrIDPasien7 = new javax.swing.JLabel();
        jLdftrNama7 = new javax.swing.JLabel();
        jLdftrtglLhr7 = new javax.swing.JLabel();
        jLdftrUmur7 = new javax.swing.JLabel();
        jTFidPasien10 = new javax.swing.JTextField();
        jTFNamaPasien10 = new javax.swing.JTextField();
        jTFtglLahirPasien10 = new javax.swing.JTextField();
        jTFUmur10 = new javax.swing.JTextField();
        JBAddPasien5 = new javax.swing.JButton();
        JBMenuUtama5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLdaftarPasien3 = new javax.swing.JLabel();
        jLdftrIDPasien1 = new javax.swing.JLabel();
        jLdftrNama1 = new javax.swing.JLabel();
        jLdftrtglLhr1 = new javax.swing.JLabel();
        jLdftrUmur1 = new javax.swing.JLabel();
        jTFidPasien4 = new javax.swing.JTextField();
        jTFNamaPasien4 = new javax.swing.JTextField();
        jTFtglLahirPasien4 = new javax.swing.JTextField();
        jTFUmur4 = new javax.swing.JTextField();
        JBAddPasien = new javax.swing.JButton();
        JBMenuUtama4 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLdaftarPasien7 = new javax.swing.JLabel();
        JBMenuUtama = new javax.swing.JButton();
        label1 = new java.awt.Label();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        JBMenuUtama3.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama3.setText("Menu Utama");
        JBMenuUtama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtama3ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLdaftarPasien6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdaftarPasien6.setText("Search Pasien by ID");

        jLdftrIDPasien4.setText("ID");

        jLdftrNama4.setText("Nama");

        jLdftrtglLhr4.setText("Tanggal Lahir");

        jLdftrUmur4.setText("Umur");

        jLdftrIDPasien9.setText("ID");

        JBSearchPasienID.setBackground(new java.awt.Color(0, 0, 255));
        JBSearchPasienID.setText("Search");

        JBMenuUtama1.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama1.setText("Menu Utama");
        JBMenuUtama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtama1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdftrtglLhr4)
                            .addComponent(jLdftrNama4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNamaPasien7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFtglLahirPasien7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLdftrUmur4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFUmur7, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLdftrIDPasien4)
                            .addComponent(jLdftrIDPasien9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFidPasien7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFidPasien12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBSearchPasienID))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(JBMenuUtama1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLdaftarPasien6)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLdaftarPasien6)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdftrIDPasien4)
                    .addComponent(jTFidPasien7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBSearchPasienID)
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFidPasien12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrIDPasien9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNamaPasien7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrNama4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFtglLahirPasien7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrtglLhr4))
                .addGap(5, 5, 5)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLdftrUmur4))
                    .addComponent(jTFUmur7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(JBMenuUtama1)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search ID", jPanel10);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLdaftarPasien11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdaftarPasien11.setText("Search Pasien by Indeks");

        jLdftrIDPasien10.setText("Indeks");

        jLdftrNama9.setText("Nama");

        jLdftrtglLhr9.setText("Tanggal Lahir");

        jLdftrUmur9.setText("Umur");

        jLdftrIDPasien11.setText("ID");

        JBAddPasien8.setBackground(new java.awt.Color(0, 0, 255));
        JBAddPasien8.setText("Search");

        JBMenuUtama2.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama2.setText("Menu Utama");
        JBMenuUtama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtama2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLdftrIDPasien10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFidPasien13, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addComponent(jLdftrIDPasien11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFidPasien14, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addComponent(jLdftrUmur9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFUmur12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addComponent(jLdftrNama9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNamaPasien12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addComponent(jLdftrtglLhr9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFtglLahirPasien12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBAddPasien8))))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLdaftarPasien11))
                            .addGroup(jPanel15Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JBMenuUtama2)))
                        .addGap(0, 143, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLdaftarPasien11)
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdftrIDPasien10)
                    .addComponent(jTFidPasien13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JBAddPasien8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTFidPasien14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLdftrIDPasien11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdftrNama9)
                    .addComponent(jTFNamaPasien12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdftrtglLhr9)
                    .addComponent(jTFtglLahirPasien12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdftrUmur9)
                    .addComponent(jTFUmur12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(JBMenuUtama2)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search Indeks", jPanel15);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLdaftarPasien9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdaftarPasien9.setText("Delete Data Pasien");

        jLdftrIDPasien7.setText("ID");

        jLdftrNama7.setText("Nama");

        jLdftrtglLhr7.setText("Tanggal Lahir");

        jLdftrUmur7.setText("Umur");

        JBAddPasien5.setBackground(new java.awt.Color(0, 0, 255));
        JBAddPasien5.setText("Delete");

        JBMenuUtama5.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama5.setText("Menu Utama");
        JBMenuUtama5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtama5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLdftrUmur7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFUmur10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLdftrtglLhr7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFtglLahirPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLdftrNama7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFNamaPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(jLdftrIDPasien7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTFidPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBAddPasien5))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(jLdaftarPasien9))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(JBMenuUtama5)))
                        .addGap(0, 163, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLdaftarPasien9)
                .addGap(39, 39, 39)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFidPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrIDPasien7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNamaPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrNama7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFtglLahirPasien10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrtglLhr7))
                .addGap(9, 9, 9)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUmur10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrUmur7))
                .addGap(18, 18, 18)
                .addComponent(JBAddPasien5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(JBMenuUtama5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Delete Data", jPanel13);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLdaftarPasien3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdaftarPasien3.setText("Daftar Pasien");

        jLdftrIDPasien1.setText("ID");

        jLdftrNama1.setText("Nama");

        jLdftrtglLhr1.setText("Tanggal Lahir");

        jLdftrUmur1.setText("Umur");

        JBAddPasien.setBackground(new java.awt.Color(0, 0, 255));
        JBAddPasien.setText("Add");

        JBMenuUtama4.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama4.setText("Menu Utama");
        JBMenuUtama4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtama4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLdftrIDPasien1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFidPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLdftrtglLhr1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFtglLahirPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLdftrNama1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFNamaPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLdftrUmur1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFUmur4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBAddPasien)
                .addGap(32, 32, 32))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLdaftarPasien3))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBMenuUtama4)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLdaftarPasien3)
                .addGap(41, 41, 41)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdftrIDPasien1)
                    .addComponent(jTFidPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLdftrNama1)
                    .addComponent(jTFNamaPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLdftrtglLhr1)
                    .addComponent(jTFtglLahirPasien4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFUmur4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLdftrUmur1))
                .addGap(18, 18, 18)
                .addComponent(JBAddPasien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(JBMenuUtama4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Pasien", jPanel7);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));

        jLdaftarPasien7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLdaftarPasien7.setText("Data Pasien");

        JBMenuUtama.setBackground(new java.awt.Color(0, 0, 255));
        JBMenuUtama.setText("Menu Utama");
        JBMenuUtama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBMenuUtamaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLdaftarPasien7))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBMenuUtama)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLdaftarPasien7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 259, Short.MAX_VALUE)
                .addComponent(JBMenuUtama)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Pasien", jPanel11);

        label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        label1.setText("Menu Pasien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBMenuUtama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMenuUtama1ActionPerformed

    private void JBMenuUtama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMenuUtama2ActionPerformed

    private void JBMenuUtama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtama3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMenuUtama3ActionPerformed

    private void JBMenuUtama4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtama4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMenuUtama4ActionPerformed

    private void JBMenuUtama5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtama5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBMenuUtama5ActionPerformed

    private void JBMenuUtamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBMenuUtamaActionPerformed
        //return
    }//GEN-LAST:event_JBMenuUtamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBAddPasien;
    private javax.swing.JButton JBAddPasien5;
    private javax.swing.JButton JBAddPasien8;
    private javax.swing.JButton JBMenuUtama;
    private javax.swing.JButton JBMenuUtama1;
    private javax.swing.JButton JBMenuUtama2;
    private javax.swing.JButton JBMenuUtama3;
    private javax.swing.JButton JBMenuUtama4;
    private javax.swing.JButton JBMenuUtama5;
    private javax.swing.JButton JBSearchPasienID;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLdaftarPasien11;
    private javax.swing.JLabel jLdaftarPasien3;
    private javax.swing.JLabel jLdaftarPasien6;
    private javax.swing.JLabel jLdaftarPasien7;
    private javax.swing.JLabel jLdaftarPasien9;
    private javax.swing.JLabel jLdftrIDPasien1;
    private javax.swing.JLabel jLdftrIDPasien10;
    private javax.swing.JLabel jLdftrIDPasien11;
    private javax.swing.JLabel jLdftrIDPasien4;
    private javax.swing.JLabel jLdftrIDPasien7;
    private javax.swing.JLabel jLdftrIDPasien9;
    private javax.swing.JLabel jLdftrNama1;
    private javax.swing.JLabel jLdftrNama4;
    private javax.swing.JLabel jLdftrNama7;
    private javax.swing.JLabel jLdftrNama9;
    private javax.swing.JLabel jLdftrUmur1;
    private javax.swing.JLabel jLdftrUmur4;
    private javax.swing.JLabel jLdftrUmur7;
    private javax.swing.JLabel jLdftrUmur9;
    private javax.swing.JLabel jLdftrtglLhr1;
    private javax.swing.JLabel jLdftrtglLhr4;
    private javax.swing.JLabel jLdftrtglLhr7;
    private javax.swing.JLabel jLdftrtglLhr9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTFNamaPasien10;
    private javax.swing.JTextField jTFNamaPasien12;
    private javax.swing.JTextField jTFNamaPasien4;
    private javax.swing.JTextField jTFNamaPasien7;
    private javax.swing.JTextField jTFUmur10;
    private javax.swing.JTextField jTFUmur12;
    private javax.swing.JTextField jTFUmur4;
    private javax.swing.JTextField jTFUmur7;
    private javax.swing.JTextField jTFidPasien10;
    private javax.swing.JTextField jTFidPasien12;
    private javax.swing.JTextField jTFidPasien13;
    private javax.swing.JTextField jTFidPasien14;
    private javax.swing.JTextField jTFidPasien4;
    private javax.swing.JTextField jTFidPasien7;
    private javax.swing.JTextField jTFtglLahirPasien10;
    private javax.swing.JTextField jTFtglLahirPasien12;
    private javax.swing.JTextField jTFtglLahirPasien4;
    private javax.swing.JTextField jTFtglLahirPasien7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
    public void addActionListener (ActionListener e){
        JBSearchPasienID.addActionListener(e);
        JBMenuUtama1.addActionListener(e);
        JBMenuUtama2.addActionListener(e);
        JBMenuUtama.addActionListener(e);
        JBMenuUtama4.addActionListener(e);
        JBMenuUtama5.addActionListener(e);
    }

    public JButton getJBAddPasien() {
        return JBAddPasien;
    }

    public void setJBAddPasien(JButton JBAddPasien) {
        this.JBAddPasien = JBAddPasien;
    }

    public JButton getJBAddPasien5() {
        return JBAddPasien5;
    }

    public void setJBAddPasien5(JButton JBAddPasien5) {
        this.JBAddPasien5 = JBAddPasien5;
    }

    public JButton getJBAddPasien8() {
        return JBAddPasien8;
    }

    public void setJBAddPasien8(JButton JBAddPasien8) {
        this.JBAddPasien8 = JBAddPasien8;
    }

    public JButton getJBMenuUtama() {
        return JBMenuUtama;
    }

    public void setJBMenuUtama(JButton JBMenuUtama) {
        this.JBMenuUtama = JBMenuUtama;
    }

    public JButton getJBMenuUtama1() {
        return JBMenuUtama1;
    }

    public void setJBMenuUtama1(JButton JBMenuUtama1) {
        this.JBMenuUtama1 = JBMenuUtama1;
    }

    public JButton getJBMenuUtama2() {
        return JBMenuUtama2;
    }

    public void setJBMenuUtama2(JButton JBMenuUtama2) {
        this.JBMenuUtama2 = JBMenuUtama2;
    }

    public JButton getJBMenuUtama3() {
        return JBMenuUtama3;
    }

    public void setJBMenuUtama3(JButton JBMenuUtama3) {
        this.JBMenuUtama3 = JBMenuUtama3;
    }

    public JButton getJBMenuUtama4() {
        return JBMenuUtama4;
    }

    public void setJBMenuUtama4(JButton JBMenuUtama4) {
        this.JBMenuUtama4 = JBMenuUtama4;
    }

    public JButton getJBMenuUtama5() {
        return JBMenuUtama5;
    }

    public void setJBMenuUtama5(JButton JBMenuUtama5) {
        this.JBMenuUtama5 = JBMenuUtama5;
    }

    public JButton getJBSearchPasienID() {
        return JBSearchPasienID;
    }

    public void setJBSearchPasienID(JButton JBSearchPasienID) {
        this.JBSearchPasienID = JBSearchPasienID;
    }

    public JInternalFrame getjInternalFrame1() {
        return jInternalFrame1;
    }

    public void setjInternalFrame1(JInternalFrame jInternalFrame1) {
        this.jInternalFrame1 = jInternalFrame1;
    }

    public JLabel getjLdftrNama9() {
        return jLdftrNama9;
    }

    public void setjLdftrNama9(JLabel jLdftrNama9) {
        this.jLdftrNama9 = jLdftrNama9;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel10() {
        return jPanel10;
    }

    public void setjPanel10(JPanel jPanel10) {
        this.jPanel10 = jPanel10;
    }

    public JPanel getjPanel11() {
        return jPanel11;
    }

    public void setjPanel11(JPanel jPanel11) {
        this.jPanel11 = jPanel11;
    }

    public JPanel getjPanel13() {
        return jPanel13;
    }

    public void setjPanel13(JPanel jPanel13) {
        this.jPanel13 = jPanel13;
    }

    public JPanel getjPanel15() {
        return jPanel15;
    }

    public void setjPanel15(JPanel jPanel15) {
        this.jPanel15 = jPanel15;
    }

    public JPanel getjPanel7() {
        return jPanel7;
    }

    public void setjPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    public JTextField getjTFNamaPasien10() {
        return jTFNamaPasien10;
    }

    public void setjTFNamaPasien10(JTextField jTFNamaPasien10) {
        this.jTFNamaPasien10 = jTFNamaPasien10;
    }

    public JTextField getjTFNamaPasien12() {
        return jTFNamaPasien12;
    }

    public void setjTFNamaPasien12(JTextField jTFNamaPasien12) {
        this.jTFNamaPasien12 = jTFNamaPasien12;
    }

    public JTextField getjTFNamaPasien4() {
        return jTFNamaPasien4;
    }

    public void setjTFNamaPasien4(JTextField jTFNamaPasien4) {
        this.jTFNamaPasien4 = jTFNamaPasien4;
    }

    public JTextField getjTFNamaPasien7() {
        return jTFNamaPasien7;
    }

    public void setjTFNamaPasien7(JTextField jTFNamaPasien7) {
        this.jTFNamaPasien7 = jTFNamaPasien7;
    }

    public JTextField getjTFUmur10() {
        return jTFUmur10;
    }

    public void setjTFUmur10(JTextField jTFUmur10) {
        this.jTFUmur10 = jTFUmur10;
    }

    public JTextField getjTFUmur12() {
        return jTFUmur12;
    }

    public void setjTFUmur12(JTextField jTFUmur12) {
        this.jTFUmur12 = jTFUmur12;
    }

    public JTextField getjTFUmur4() {
        return jTFUmur4;
    }

    public void setjTFUmur4(JTextField jTFUmur4) {
        this.jTFUmur4 = jTFUmur4;
    }

    public JTextField getjTFUmur7() {
        return jTFUmur7;
    }

    public void setjTFUmur7(JTextField jTFUmur7) {
        this.jTFUmur7 = jTFUmur7;
    }

    public JTextField getjTFidPasien10() {
        return jTFidPasien10;
    }

    public void setjTFidPasien10(JTextField jTFidPasien10) {
        this.jTFidPasien10 = jTFidPasien10;
    }

    public JTextField getjTFidPasien12() {
        return jTFidPasien12;
    }

    public void setjTFidPasien12(JTextField jTFidPasien12) {
        this.jTFidPasien12 = jTFidPasien12;
    }

    public JTextField getjTFidPasien13() {
        return jTFidPasien13;
    }

    public void setjTFidPasien13(JTextField jTFidPasien13) {
        this.jTFidPasien13 = jTFidPasien13;
    }

    public JTextField getjTFidPasien14() {
        return jTFidPasien14;
    }

    public void setjTFidPasien14(JTextField jTFidPasien14) {
        this.jTFidPasien14 = jTFidPasien14;
    }

    public JTextField getjTFidPasien4() {
        return jTFidPasien4;
    }

    public void setjTFidPasien4(JTextField jTFidPasien4) {
        this.jTFidPasien4 = jTFidPasien4;
    }

    public JTextField getjTFidPasien7() {
        return jTFidPasien7;
    }

    public void setjTFidPasien7(JTextField jTFidPasien7) {
        this.jTFidPasien7 = jTFidPasien7;
    }

    public JTextField getjTFtglLahirPasien10() {
        return jTFtglLahirPasien10;
    }

    public void setjTFtglLahirPasien10(JTextField jTFtglLahirPasien10) {
        this.jTFtglLahirPasien10 = jTFtglLahirPasien10;
    }

    public JTextField getjTFtglLahirPasien12() {
        return jTFtglLahirPasien12;
    }

    public void setjTFtglLahirPasien12(JTextField jTFtglLahirPasien12) {
        this.jTFtglLahirPasien12 = jTFtglLahirPasien12;
    }

    public JTextField getjTFtglLahirPasien4() {
        return jTFtglLahirPasien4;
    }

    public void setjTFtglLahirPasien4(JTextField jTFtglLahirPasien4) {
        this.jTFtglLahirPasien4 = jTFtglLahirPasien4;
    }

    public JTextField getjTFtglLahirPasien7() {
        return jTFtglLahirPasien7;
    }

    public void setjTFtglLahirPasien7(JTextField jTFtglLahirPasien7) {
        this.jTFtglLahirPasien7 = jTFtglLahirPasien7;
    }

    public JTabbedPane getjTabbedPane1() {
        return jTabbedPane1;
    }

    public void setjTabbedPane1(JTabbedPane jTabbedPane1) {
        this.jTabbedPane1 = jTabbedPane1;
    }
    
}
